name: Auto Assign PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run assign reviewers script
        uses: actions/github-script@v7
        env:
          COLLABORATORS: ${{ secrets.COLLABORATORS }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_MENTION: ${{ secrets.DISCORD_MENTION }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('.github/scripts/assign-reviewer.cjs');
            await script({ github, context, core });
