name: Auto Send Discord Review Reminder

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  pr-management:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: read
      checks: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Reminder to Discord
        uses: actions/github-script@v7
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_MENTION: ${{ secrets.DISCORD_MENTION }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('.github/scripts/auto-review-alarm.cjs');
            await script({ github, context, core });
